const types = {
    //global
    SET_TRANSITIONNAME: 'SET_TRANSITIONNAME',
    SET_LOADING: 'SET_LOADING',
    SET_PREVIEW: 'SET_PREVIEW',
    SET_AUDIOSRC: 'SET_AUDIOSRC',
    SET_AUDIOSTATUS: 'SET_AUDIOSTATUS',

    //user
    USER_REGISTER: 'USER_REGISTER',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGINOUT: 'USER_LOGINOUT',
    GET_USERINFO: 'GET_user_info',
    UPDATE_USERINFO: 'UPDATE_USERINFO',

    //article
    GET_TOPREADINGARTICLE: 'GET_TOPREADINGARTICLE',
    GET_TOPFILMARTICLE: 'GET_TOPFILMARTICLE',
    GET_TOPMUSICARTICLE: 'GET_TOPMUSICARTICLE',
    GET_TOPSOUNDARTICLE: 'GET_TOPSOUNDARTICLE',
}

export default types
